# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82cf68ff3b1b7b6b7807972341c8e7c12960855524092e801b4ff94d7617a405ff9ebd242af1b8cb8c86f04e2a4e5f18c7b469da0dd856e28c27b615d17fea93

test:
  secret_key_base: 91a49883cda3631d84034a7f50cdaecac5144ece1e4fde8f71f23ec4f9eed98db1199049ba76c06bd243f11d628739474a73c17625b28685a00f9bb090919689

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
